[ESSI-1338] Log profile import separately, and provide in UI
IU-Libraries-Joint-Development/essi pull request #308
Opened 2021-06-04 15:44 UTC by aploshay

Extension to PR #305

2021-06-09 20:35 UTC, dlpierce commented
In the container the Rails log is output to stdout, but writing to a separate log as done here should still work with the caveat that it would not be retained between service restarts. Making the log location configurable would be good as that would allow it to reside on a different storage volume.

2021-06-09 20:36 UTC, dlpierce requested changes

2021-06-09 20:36 UTC, dlpierce commented on lib/extensions/allinson_flex/prepend_importer.rb
> +        @validation_logger ||= Logger.new(Rails.root.join('log', 'profile_validation.log'), 10, 2.megabytes)
Add log location configuration

2021-06-10 15:49 UTC, aploshay commented on lib/extensions/allinson_flex/prepend_importer.rb
> +        @validation_logger ||= Logger.new(Rails.root.join('log', 'profile_validation.log'), 10, 2.megabytes)
@dlpierce configuration added

2021-06-10 16:58 UTC, dlpierce approved these changes

2021-06-10 16:59 UTC, merged