Essi 1337
IU-Libraries-Joint-Development/essi pull request #325
Opened 2021-07-20 14:48 UTC by nianma

2021-07-20 16:25 UTC, aploshay requested changes
Requesting changes:
- remove commented lines referencing feature version of API, file authority
- record new VCR cassette to replace one referencing old API

2021-07-21 04:44 UTC, aploshay approved these changes

2021-07-21 04:47 UTC, aploshay commented
Reverting to draft pending Nick confirming if he wants the campus render to link to the campus page, to facet search by campus, or something else, or not at all.

2021-07-27 15:05 UTC, randalldfloyd approved these changes

2021-07-27 15:27 UTC, merged